### PR TITLE
add support for send and receive use different protocol

### PR DESCRIPTION
**Pull request by comwrg**
https://github.com/v2ray/v2ray-core/issues/1388

### CODE REVIEW

**Comment by VictoriaRaymond** [comment]
This is a big change. Please write a document about your plan, and review it with dev team. Such PR will not be simply accepted.

**Comment by comwrg** [comment]
Ok, I'll try.

**Comment by comwrg** [comment]
### My Plan

In client, using TCP as send protocol and mKCP or QUIC as receive protocol.
We consider the send protocol and the receive protocol is reliable so we not consider internal of protocol.

Client needs to do
1. Establish a connection using send protocol.
2. Sending heartbeat packets using receive protocol per 60s for keeping NAT port mapping.
3. Generate an UUID and send the UUID using the send protocol and the receive protocol respectively to make server link two connections, server need to record the client's receive ip and port.

Then, when client sends request data to server using send protocol, the server will send data to the client's ip and port using the client's receive protocol after gets response data.

**Comment by VictoriaRaymond** [comment]
What is the benefit to split uplink and downlink? In your proposal, the connections are 1:1 mapped between uplink and downlink. Both connections has some-what obvious fingerprint (UUID and heartbeat).

**Comment by comwrg** [comment]
Goal is solve the uplink UDP QoS.

Uplink data can be encrypted by some encryption protocols so UUID not is an obvious fingerprint I think.

**Pull request closed without merging**
